### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by CGuichard** [EOEPCA/system-architecture#3]
While browsing and exploring the documentation I felt a little frustrated by the absence of a search bar.

Would it be possible to add the following config to `mkdocs.yml`?

```yaml
theme:
  features:
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search
```

I think it would also be relevant in the [documentation-template](https://github.com/EOEPCA/document-template).
